### ISSUE TITLE
点击使用报错

### ISSUE THREAD

**Issue by Nicksxs** [jenkinsci/localization-zh-cn-plugin#123]
java.io.FileNotFoundException: /var/lib/jenkins/war/WEB-INF/update-center-rootCAs/mirror-adapter.crt (No such file or directory)

**Comment by LinuxSuRen** [comment]
麻烦提供下可以复现您遇到的问题的步骤，谢谢。

**Comment by Nicksxs** [comment]
点击获取更新时报错
检查更新中心: Signature verification failed in update site &#039;default&#039; <a href='#' class='showDetails'>（显示详情）</a><pre style='display:none'>java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors<br> at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:154)<br> at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:80)<br> at java.security.cert.CertPathValidator.validate(CertPathValidator.java:292)<br> at org.jvnet.hudson.crypto.CertificateUtil.validatePath(CertificateUtil.java:93)<br> at jenkins.util.JSONSignatureValidator.verifySignature(JSONSignatureValidator.java:88)<br> at hudson.model.UpdateSite.verifySignature(UpdateSite.java:254)<br> at hudson.model.UpdateSite.updateData(UpdateSite.java:218)<br> at hudson.model.UpdateSite.updateDirectlyNow(UpdateSite.java:189)<br> at hudson.PluginManager.checkUpdatesServer(PluginManager.java:1763)<br> at hudson.util.Retrier.start(Retrier.java:62)<br> at hudson.PluginManager.doCheckUpdatesServer(PluginManager.java:1734)<br> at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)<br> at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)<br> at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:408)<br> at org.kohsuke.stapler.interceptor.RequirePOST$Processor.invoke(RequirePOST.java:77)<br> at org.kohsuke.stapler.PreInvokeInterceptedFunction.invoke(PreInvokeInterceptedFunction.java:26)<br> at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:212)<br> at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:145)<br> at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:535)<br> at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)<br> at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:747)<br> at org.kohsuke.stapler.Stapler.invoke(Stapler.java:878)<br> at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:169)<br> at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)<br> at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:747)<br> at org.kohsuke.stapler.Stapler.invoke(Stapler.java:878)<br> at org.kohsuke.stapler.Stapler.invoke(Stapler.java:676)<br> at org.kohsuke.stapler.Stapler.service(Stapler.java:238)<br> at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)<br> at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)<br> at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)<br> at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)<br> at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:128)<br> at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)<br> at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)<br> at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)<br> at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:99)<br> at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)<br> at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)<br> at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)<br> at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)<br> at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)<br> at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)<br> at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)<br> at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)<br> at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)<br> at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)<br> at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)<br> at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)<br> at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)<br> at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)<br> at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)<br> at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)<br> at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)<br> at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)<br> at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)<br> at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)<br> at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)<br> at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)<br> at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)<br> at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)<br> at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)<br> at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)<br> at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)<br> at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)<br> at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)<br> at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)<br> at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)<br> at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)<br> at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)<br> at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)<br> at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)<br> at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)<br> at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)<br> at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)<br> at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)<br> at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)<br> at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)<br> at org.eclipse.jetty.server.Server.handle(Server.java:505)<br> at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)<br> at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)<br> at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)<br> at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)<br> at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)<br> at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)<br> at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)<br> at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)<br> at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)<br> at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)<br> at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)<br> at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)<br> at java.lang.Thread.run(Thread.java:748)<br></pre> 时发生错误

**Comment by LinuxSuRen** [comment]
更新为最新版本再试试，或者可以在[官方论坛](https://community.jenkins-zh.cn/t/jenkins/26/23)里讨论遇到的问题。
