### ISSUE TITLE
通过docker安装的jenkins安装此插件无效

### ISSUE THREAD

**Issue by yidasanqian** [jenkinsci/localization-zh-cn-plugin#125]
<img width="803" alt="Screen Shot 2020-02-08 at 14 49 28" src="https://user-images.githubusercontent.com/10655188/74080760-6e99d280-4a82-11ea-99bf-799eeaaacbf1.png">

根据这篇文章操作的，没看到效果啊
https://jenkins-zh.cn/wechat/articles/2019/11/2019-11-11-update-center-mirror-announcement/

<img width="1070" alt="Screen Shot 2020-02-08 at 14 51 40" src="https://user-images.githubusercontent.com/10655188/74080766-8e30fb00-4a82-11ea-9eb3-36791cada637.png">

**Comment by LinuxSuRen** [comment]
这里有很多这方面的讨论。
