### ISSUE TITLE
请求更改Footer中“Jenkins 中文社区”字样的样式

### ISSUE THREAD

**Issue by jim-kirisame** [jenkinsci/localization-zh-cn-plugin#136]
当前这一字符串与Jenkins默认底栏样式不一致，就好像是强制注入的东西一样。

期望要么弄成一致的样式，要么直接删除这一字样。

**Comment by LinuxSuRen** [comment]
临时方案，你可以关闭这个的显示。如果您有时间的话，可以帮忙修复下，或者再等等后续的优化。
![image](https://user-images.githubusercontent.com/1450685/92102044-9e3e6c80-ee10-11ea-822a-5b3968a0a2ca.png)

**Comment by LinuxSuRen** [comment]
It can be fixed by two PRs
upstream jenkinsci/jenkins#4949 and #143
